dist: trusty
env:
  global:
    PUBLISH_NPM_LATEST_FROM="master"
sudo: false
language: node_js
node_js:
  - "10.0.0"

before_install:
  - echo 'before install'
  - npm i -g npm@6.4.1  
  - yarn global add webpack 
script:
  - echo 'about to yarn test *****************'
  - yarn test
  - echo 'about to call run_tests -------'
  - cd dist && ./run_tests.sh
  - echo 'done ----------'
deploy:
  - provider: script
    skip_cleanup: false
    script: echo "deploy!!!!"
      # - echo 'about to call publish-edge**************'
      # - pwd
      # - ./scripts/publish-edge.sh
    on:
      all_branches: true
  # - provider: script
  #   skip_cleanup: true
  #   script:
  #     - ./scripts/publish-tag.sh $PUBLISH_NPM_LATEST_FROM
  #   on:
  #     tags: true
  #     condition: "$TRAVIS_TAG =~ ^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
